sudo: required
services:
- docker
language: go
go:
- '1.5'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: j0m1fqgdlOEjxWOVdbSkHa0Tj7idMM6plJqnQCpcuIcwqh83Scs+6wyuF7JZeCXiRHfrZg6X7q4Rfs4ItAsakp9YZEaFdsgyxWow1X2GsIXu3IoDHxc6A+nwTS/GRk/w1tuEnMNYfuHc4HIuF1NYC5RqElsXAZ+iaimEgY8Pqwyr2osyIYl0HgsT3oMG0DD97IihxTaLkTlSHPyjIjJJlOcs6VFnCGRgeKgsdRI87ldvLDz5DLx6q6IcUh3vDWnlZaOvm/0UJaxkvfrNVKW9dLzizweTSpy6WHs5/lTitXIsX6/oxW530AXlB7Ghi9e7ZULvQua0z0ycOunsuTmC9daCNtr4tyvK7Wsn/e2dcUOiDQEIQi7OQ+Y9tNLqaC5XJqkzQ2n92TeTGq3OB8B/bl/u3hIOka1GfGzIwXnklWGQqX4Pa/QiMppt158G3/qshNBITpNkla+zyceAP//xtNpQQjnzA8klYWF0g/uZLK8vIxEJjJeBL4PAuqschMW8RuzwaJmlXH1NEynv3osZWJVR8pf3GTp2TnpOpXOBR8Vc/JmTsQagDJfoy8FgzUDNMK/+92YTHxo6P/yKCV8MnL7vodWySsg0N+SYa7/5Hwxwa6IhsQJHmJTDMoPmdAqwHXvsdw3WMcDUSQOnUEuiBDM6PR5N8E9O9cFUKYCULgk=
  - secure: iYkBZvyusxqLPtUrJi8WyO4vMxIYpw5rXuJAwX7TNYW8RXKZ1/3H2L2o8IxgV6C9s1JLHxD6bJ1kk3cRPt9FcTZxeGQVuzv8aSUPBfjr38ihIY5ovoqL3d8i+GOVl5E3ja6gQ5GJ28WdY3mMyIIWMMtr9oTaSEZw5m30O2y4hMzX7rZ9MwhriIzrhizYyDJwiehJ1qOp2w+BLm/dt3CFtra7KpBndMt4TpSeTk0BSdBVqrOWN18L8qOhmy8OSrITIWNz/rPZ40LssphrPyJC4kJIOiwKxVZQuBmFbbrqfzCaWv7kBV0lLno3Xbyy7Fnwe3jVG0Tke5McZexcl1+bCQTtjKZ9wQhi+DBNBz2vAEOAQQ2LD2SF3m9R0ho0/kl8FTBXl9kk/6+PFv8ZGOgGUjQ5ljmoQWL5GZIgh4tIgRB0XJ5I1KVNjdqCkemUcwXo3gW2VS5TqqPw3k+GuYXIHGUTVNrHgZEx5lzOXZ97oczc1PwX5Ep9QJR1UuHWuulqSSNz4LLAgO0swIGUK4t7SQrO43iQyBrta0Qd/0UDLayb1C4agqzs8zvcYKmJDP+QJL0irAcnCrsI4f5hK/C69C60yRGn+CVIqYuEmMMk2jbYnr/4uBgDV70D9COv4Tz+UuOlypla5MXCxa7rqateCSM7EQbC9Gh1uw1/l38nu5g=
  - secure: UNolzyAQDp4OZ+4kKIXn7O1CBVrrz1y78gCpxzX5A1L8oCYr/7zgE3VKOCR2lR1SPn7+oKPT2Jo0XD07hKPag1IQXRZC3SZ6RQ3Ud4fm0auoDUtpDDl2mHYkkuEimCu/+fORQZ5DIwku/Zt3LNASajcaeka9YoeLx3zV5PNONHRMHywGIFMGxYH/FSDPibHsaPN8epaeYRAJipsSJZ960qpax25JS+GA7b0hHmxRDhN2YhT1YwqDb3sSl18fRJVpOg0GtvoYWBzzCeraFTXpHEVGK2YQkLrer+Ng7TpUQnI375mYDiMuRob8YCvN1TJlTgs7Gi8AvjOdPbeIj/G/bZiFZvNSjBY2LW5/+mWYZ2WqBhuGtFkUUXYzSv71tIQAMDD2sY98nBpL3CB4Vny84Bk+ZRmuxb7doPWVgVQKFfkyC9Z0vHCnRCz+pOrY2c1oHjbfp4rosZ+L8zHUcJ7ssU1EH/W77c50MX5tPaTEWI3LaHpcDiV0K4EyTpTeWjbJDXvMQRodv8mIowy2UTKLZ9iuicV9mm/YpqXtbq7UhOEX8gYac3ytIdx+sMD1qto7uywAXsOV0Ov9KZN7wJGMH5HSXoPoXwsH21Oz8LMBxeQRfoyFzVej9cEt1IL9t+Fp0ZHBw1n2Muet+hkyE7LROD/pr6IBYPXFpMnDQddqXxI=
after_success:
- CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=gfleury/elasticsearch-oss
- export TAG=`if [ "$TRAVIS_BRANCH" == "es_tsuru" ]; then echo "latest"; else echo
  $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
